class_names = ['AllerDisplay', 'Aller_Bd', 'Aller_BdIt', 'Aller_It', 'Aller_Lt', 
    'Aller_LtIt', 'Aller_Rg', 'Amatic-Bold', 'AmaticSC-Regular', 'BEBAS___', 
    'Capture_it', 'Capture_it_2', 'CaviarDreams', 'CaviarDreams_BoldItalic', 
    'CaviarDreams_Italic', 'Caviar_Dreams_Bold', 'DroidSans', 'DroidSans-Bold',
    'FFF_Tusj', 'Lato-Black', 'Lato-BlackItalic', 'Lato-Bold', 'Lato-BoldItalic',
    'Lato-Hairline', 'Lato-HairlineItalic', 'Lato-Heavy', 'Lato-HeavyItalic', 
    'Lato-Italic', 'Lato-Light', 'Lato-LightItalic', 'Lato-Medium', 
    'Lato-MediumItalic', 'Lato-Regular', 'Lato-Semibold', 'Lato-SemiboldItalic',
    'Lato-Thin', 'Lato-ThinItalic', 'OpenSans-Bold', 'OpenSans-BoldItalic', 
    'OpenSans-ExtraBold', 'OpenSans-ExtraBoldItalic', 'OpenSans-Italic', 
    'OpenSans-Light', 'OpenSans-LightItalic', 'OpenSans-Regular', 
    'OpenSans-Semibold', 'OpenSans-SemiboldItalic', 'Pacifico', 'Raleway-Black', 
    'Raleway-BlackItalic', 'Raleway-Bold', 'Raleway-BoldItalic', 
    'Raleway-ExtraBold', 'Raleway-ExtraBoldItalic', 'Raleway-ExtraLight', 
    'Raleway-ExtraLightItalic', 'Raleway-Italic', 'Raleway-Light', 
    'Raleway-LightItalic', 'Raleway-Medium', 'Raleway-MediumItalic', 
    'Raleway-Regular', 'Raleway-SemiBold', 'Raleway-SemiBoldItalic', 
    'Raleway-Thin', 'Raleway-ThinItalic', 'Roboto-Black', 'Roboto-BlackItalic', 
    'Roboto-Bold', 'Roboto-BoldItalic', 'Roboto-Italic', 'Roboto-Light', 
    'Roboto-LightItalic', 'Roboto-Medium', 'Roboto-MediumItalic', 'Roboto-Regular', 
    'Roboto-Thin', 'Roboto-ThinItalic', 'RobotoCondensed-Bold', 
    'RobotoCondensed-BoldItalic', 'RobotoCondensed-Italic', 'RobotoCondensed-Light', 
    'RobotoCondensed-LightItalic', 'RobotoCondensed-Regular', 'SEASRN__', 
    'Sansation-Bold', 'Sansation-BoldItalic', 'Sansation-Italic', 'Sansation-Light', 
    'Sansation-LightItalic', 'Sansation-Regular', 'Walkway_Black', 'Walkway_Bold', 
    'Walkway_Oblique', 'Walkway_Oblique_Black', 'Walkway_Oblique_Bold', 
    'Walkway_Oblique_SemiBold', 'Walkway_Oblique_UltraBold', 'Walkway_SemiBold', 
    'Walkway_UltraBold']