from data_generator.generators.from_dict import GeneratorFromDict
from data_generator.generators.from_random import GeneratorFromRandom
from data_generator.generators.from_strings import GeneratorFromStrings
from data_generator.generators.from_wikipedia import GeneratorFromWikipedia
